In [14]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [15]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.73890265 0.85067296 0.24734752]
 [0.44621704 0.02985007 0.64864034]
 [0.19683127 0.51316358 0.25242015]]


In [16]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


### Some assignment problems

In [23]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''

'\nCreate an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.\nThen reshape it to a (9, 2) array and take its transpose. \nFind the locations where all elements are greater than the mean of the array and print it\n'

In [24]:
random_arr = np.random.rand(3, 6)
add_array = np.array([0, 0, 2, 4, 5, 3])

result = random_arr + add_array
reshaped = result.reshape(9, 2)
transposed = reshaped.T

mean_val = np.mean(transposed)
locations = np.where(transposed > mean_val)

print("Original random array (3, 6):")
print(random_arr)
print("\nAfter adding [0, 0, 2, 4, 5, 3] to each row:")
print(result)
print("\nReshaped to (9, 2):")
print(reshaped)
print("\nTransposed:")
print(transposed)
print(f"\nMean of transposed array: {mean_val:.4f}")
print("\nLocations where elements are greater than mean:")
print(f"Row indices: {locations[0]}")
print(f"Column indices: {locations[1]}")
print("\nElements greater than mean:")
print(transposed[locations])

Original random array (3, 6):
[[0.75855705 0.02954715 0.20086007 0.76514021 0.27691552 0.53272987]
 [0.10656144 0.02404499 0.46979184 0.58817157 0.17528474 0.51914081]
 [0.25774432 0.85357184 0.76412714 0.30836345 0.83224392 0.51817109]]

After adding [0, 0, 2, 4, 5, 3] to each row:
[[0.75855705 0.02954715 2.20086007 4.76514021 5.27691552 3.53272987]
 [0.10656144 0.02404499 2.46979184 4.58817157 5.17528474 3.51914081]
 [0.25774432 0.85357184 2.76412714 4.30836345 5.83224392 3.51817109]]

Reshaped to (9, 2):
[[0.75855705 0.02954715]
 [2.20086007 4.76514021]
 [5.27691552 3.53272987]
 [0.10656144 0.02404499]
 [2.46979184 4.58817157]
 [5.17528474 3.51914081]
 [0.25774432 0.85357184]
 [2.76412714 4.30836345]
 [5.83224392 3.51817109]]

Transposed:
[[0.75855705 2.20086007 5.27691552 0.10656144 2.46979184 5.17528474
  0.25774432 2.76412714 5.83224392]
 [0.02954715 4.76514021 3.53272987 0.02404499 4.58817157 3.51914081
  0.85357184 4.30836345 3.51817109]]

Mean of transposed array: 2.7767

Loca

In [25]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

'\nCreate an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation\n(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)\n'

In [26]:
poisson_arr = np.random.poisson(lam=5, size=20)

mean_val = np.mean(poisson_arr)
std_val = np.std(poisson_arr)

centered = poisson_arr - mean_val
normalized = centered / std_val

print("Original Poisson array:")
print(poisson_arr)
print(f"\nMean: {mean_val:.4f}")
print(f"Standard Deviation: {std_val:.4f}")
print("\nCentered array (subtracted mean):")
print(centered)
print("\nNormalized array (divided by std):")
print(normalized)
print(f"\nMean of normalized array: {np.mean(normalized):.4f}")
print(f"Std of normalized array: {np.std(normalized):.4f}")

Original Poisson array:
[ 4  2  3  5  5  9  1  8  2  5 11  1  6  9  6  5  6  6  6  5]

Mean: 5.2500
Standard Deviation: 2.6053

Centered array (subtracted mean):
[-1.25 -3.25 -2.25 -0.25 -0.25  3.75 -4.25  2.75 -3.25 -0.25  5.75 -4.25
  0.75  3.75  0.75 -0.25  0.75  0.75  0.75 -0.25]

Normalized array (divided by std):
[-0.47979431 -1.2474652  -0.86362975 -0.09595886 -0.09595886  1.43938292
 -1.63130065  1.05554748 -1.2474652  -0.09595886  2.20705382 -1.63130065
  0.28787658  1.43938292  0.28787658 -0.09595886  0.28787658  0.28787658
  0.28787658 -0.09595886]

Mean of normalized array: 0.0000
Std of normalized array: 1.0000
